name: Portainer deployment to karazhan
run-name: Deployment job Portainer to karazhan - ${{ github.actor }}

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - run: echo "hello"
