name: Portainer deployment job
run-name: Deployment of a portainer service - ${{ github.actor }}

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.CLOUD_INIT_KEY }}" | ssh-add -
          ssh -o StrictHostKeyChecking=no ${{ vars.KARAZHAN_USER }}@${{ vars.KARAZHAN_DNS }} << 'EOF'
            cd repos
            mkdir test_ssh
          EOF
